version: "3.9"

services:
  app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./app:/app
      - ./assets:/app/assets/img/uploads
    restart: always

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
